steps:
- name: "node:16.15.0"
  dir: "webapp"
  entrypoint: npm
  args: ["install"]
- name: "node:16.15.0"
  dir: "webapp"
  entrypoint: npm
  args: [ "run", "create-env"]
  env:
    - 'SECRET_OR_KEY=${_SECRET_OR_KEY}'
    - 'API=${_API}'
    - 'PORT=${_PORT}'
- name: "node:16.15.0"
  dir: "webapp"
  entrypoint: npm
  args: ["run", "build"]
- name: "gcr.io/cloud-builders/gcloud"
  dir: "webapp"
  args: ["app", "deploy", "--project", "motogym-online-web"]
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY
