steps:
- name: "gcr.io/cloud-builders/npm"
  args: ["i", "-w", "api"]
- name: "gcr.io/cloud-builders/npm"
  entrypoint: npm
  args: [ "run", "create-env", "-w", "api"]
  env:
    - 'MONGO_DB_NAME=${_MONGO_DB_NAME}'
    - 'MONGO_HOST=${_MONGO_HOST}'
    - 'MONGO_USER=${_MONGO_USER}'
    - 'MONGO_PASSWORD=${_MONGO_PASSWORD}'
    - 'SECRET_OR_KEY=${_SECRET_OR_KEY}'
    - 'TRANSPORT_AUTH_USER=${_TRANSPORT_AUTH_USER}'
    - 'TRANSPORT_AUTH_PASS=${_TRANSPORT_AUTH_PASS}'
    - 'BUCKET_NAME=${_BUCKET_NAME}'
    - 'DEV_USER_EMAIL=${_DEV_USER_EMAIL}'
    - 'SITE_ROOT_URL=${_SITE_ROOT_URL}'
    - 'AWS_BUCKET_NAME=${_AWS_BUCKET_NAME}'
    - 'AWS_BUCKET_REGION=${_AWS_BUCKET_REGION}'
    - 'AWS_ARN=${_AWS_ARN}'
    - 'AWS_ACCESS_KEY_ID=${_AWS_ACCESS_KEY_ID}'
    - 'AWS_SECRET_ACCESS_KEY=${_AWS_SECRET_ACCESS_KEY}'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "--project", "motogym-online-api"]
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY
