steps:
- name: "node:16.15.0"
  entrypoint: npm
  args: ["i", "-w", "api"]
- name: "node:16.15.0"
  entrypoint: npm
  args: [ "run", "create-env", "-w", "api"]
  env:
    - 'MONGO_URI=${_MONGO_URI}'
    - 'MONGO_DB=${_MONGO_DB}'
    - 'ACCESS_TOKEN_SECRET=${_ACCESS_TOKEN_SECRET}'
    - 'REFRESH_TOKEN_SECRET=${_REFRESH_TOKEN_SECRET}'
    - 'RANDOM_TOKEN_SECRET=${_RANDOM_TOKEN_SECRET}'
    - 'TRANSPORT_AUTH_USER=${_TRANSPORT_AUTH_USER}'
    - 'TRANSPORT_AUTH_PASS=${_TRANSPORT_AUTH_PASS}'
    - 'BUCKET_NAME=${_BUCKET_NAME}'
    - 'DEV_USER_EMAIL=${_DEV_USER_EMAIL}'
    - 'ORIGIN=${_ORIGIN}'
    - 'AWS_BUCKET_NAME=${_AWS_BUCKET_NAME}'
    - 'AWS_BUCKET_REGION=${_AWS_BUCKET_REGION}'
    - 'AWS_ARN=${_AWS_ARN}'
    - 'AWS_ACCESS_KEY_ID=${_AWS_ACCESS_KEY_ID}'
    - 'AWS_SECRET_ACCESS_KEY=${_AWS_SECRET_ACCESS_KEY}'
- name: "gcr.io/cloud-builders/gcloud"
  dir: "api"
  args: ["app", "deploy", "--project", "motogym-online-api"]
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY
