steps:
- name: "gcr.io/cloud-builders/npm"
  args: ["install"]
- name: "gcr.io/cloud-builders/npm"
  entrypoint: npm
  args: [ "run", "create-env" ]
  env:
    - 'MONGO_DB_NAME=${_MONGO_DB_NAME}'
    - 'MONGO_USER=${_MONGO_USER}'
    - 'MONGO_PASSWORD=${_MONGO_PASSWORD}'
    - 'SECRET_OR_KEY=${_SECRET_OR_KEY}'
    - 'TRANSPORT_AUTH_USER=${_TRANSPORT_AUTH_USER}'
    - 'TRANSPORT_AUTH_PASS=${_TRANSPORT_AUTH_PASS}'
    - 'BUCKET_NAME=${_BUCKET_NAME}'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "--project", "motogym-online-api"]
timeout: "1600s"